#!/bin/sh
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
set starter { ${1:+"$@"}
    shift
    shift
    export AUTOTEST
    AUTOTEST="${AUTOTEST-/autons/autotest}"
    exec $AUTOTEST/bin/expect -f $0 -- ${1:+"$@"}
}
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
##s
# $Id: alias2emacs,v 1.1 2006/06/24 17:54:41 tennis Exp $
# Copyright (c) 2006Cisco Systems, Inc.
#
# Name:
# ~~~~~
#     alias2emacs
#
#
# Purpose:
# ~~~~~~~~
#     This is a trivial little utility that converts the contents of the file
#     "testbeds_alias" to a format that can be used as aliases for emacs.
#
#
# Description:
# ~~~~~~~~~~~~
#
# The output of this utility can be pasted into the emacs lisp function below.
# Then the function can be pasted into your .emacs file.  After restarting
# emacs, you can then access any of the routers defined by simply typing
# esc-x <router name>.
#
# Example:
#   esc-x hfw
#
# Where:
#   esc-x is Escape key followed by the "x" key
#   hfw is an abbreviation of testbed h's firewall.
#
# Lisp Function:
#
#           (mapc
#            (lambda (x)
#              (fset (car x)
#                    (list
#                     'lambda () (nth 1 x)
#                     '(interactive) (nth 1 x)
#                     `(telnet ,(nth 1 x))
#                     `(rename-buffer ,(nth 2 x)))))
#            '(
#              ;; ------------------------------------------
#                            Paste output here
#              ;; ------------------------------------------#
#              ))
# Author:
# ~~~~~~~
#    Tennis Smith
#
#
# Notes/ToDo:
# ~~~~~~~~~~~
#   - Allow the user to pick the alias file instead of assuming the name.
#
# End of Header

package require fileutil
global env

set FIND_ALIAS_DEFS {^alias +ipsec[a-z]}
set EXTRACT_TESTBEDS_AND_PORTS \
    {^.*:[0-9]+:alias +ipsec([a-z])-([a-zA-Z0-9\" -]+)}
set INSERT_TESTBED_AND_PORT {\1\2}

set aliases [::fileutil::grep $FIND_ALIAS_DEFS \
                 $env(AUTOTEST)/stg_reg/utils/testbeds_alias]

foreach line $aliases {

    regsub -- \
        $EXTRACT_TESTBEDS_AND_PORTS $line \
        $INSERT_TESTBED_AND_PORT new_line

    regsub -- {telnet} $new_line {} new_line

    foreach { rtr telnet_port } $new_line break
    puts "[format "\(%-8s    \"%-20s\"   \"%s\"\)"\
            $rtr $telnet_port $rtr]"
}



# -----------------------------------------------------------------------------
#                            CVS MAINTENANCE LOGS
#                            ~~~~~~~~~~~~~~~~~~~~
# $Log: alias2emacs,v $
# Revision 1.1  2006/06/24 17:54:41  tennis
# initial commit
#
#
# -----------------------------------------------------------------------------
# Local Variables:
# mode: tcl
# End:
