#!/bin/sh
# \
exec /usr/local/bin/tclsh "$0" ${1+"$@"}

###############################################################
#
# Tool used to check for codecheck violations on recent commits
# Run as a cron job nightly
# Sends email to violators
#
###############################################################

# Main Code

# Target directory list for checking
set check_area [list \
                /auto/stg-devtest/eArms/regression/tests/functionality/ipsec \
                /auto/stg-devtest/eArms/stg_reg/utils \
               ]
# Admins
set admins "gicarval"

# Reference date - any commit previous to this date will be ignored
set ref_date 20060101

# Temp email files
set owner_file /tmp/owner_codecheck_notify
set admin_file /tmp/admin_codecheck_notify

# Create email subjects
set owner_subject "*** PLEASE FIX - Codecheck errors on recent commit"
set admin_subject "Codecheck -  Error notifications to the following:"

# Consider only the files changed by the current members of IOS crypto devtest
# team
set active_owners "gicarval lakshmik dheron reynoldj tennis inasingh cluo \
                   nandigam gja mshirali siddesai abgoel jgunturi dsomasun \
                   dguedesp tidacost"

# Open admin file
set admin_fid [open $admin_file w+]
set admin_list "\nOwner followed by file with errors:\n\n"

# Keep track of all files for which we cannot find a owner that belongs to
# IOS crypto devtest group
set orphan_file_list "\n====================================================== \
                      \n\nList of files that are not owned by any of the \
                      current members in IOS crypto devtest group:\n\n"

# Keep track of the old commited files with errors but for which no notification
# email gets triggered
set old_commits_list "\n====================================================== \
                      \n\nList of files with errors but that were commited \
                      before $ref_date (no notification sent to author):\n\n"

# Run codecheck on files in desired areas
foreach area $check_area {
    cd $area
    puts "Checking $area ..."
    if { [ ::catch {
        # Get list of files
        set files [glob ipsec* *.exp]

        #
        # FIXME --- Change this to something like "cvs status | grep ^File"
        # and pull out the file names.  Extra points for setting error
        # message if the file is not updated.
        # Also, use the cvs status utils in encoreutils.  Walk thru all
        # files in the dir, and do a status on each.  Anything that isn't in
        # cvs should have the last userid that touched it notified to get rid
        # of the file.


    } err ] } {
        puts "Error: $err"
        continue
    }
    foreach file $files {
        puts "Checking file $file ..."
        # FIXME
        # Glean the "author" value by putting in a filename table/lookup
        # util call here.  If no author found, then use the last id that
        # touched it.
        #

        # Get committers from CVS
        if {[catch {set author_list [exec cvs log $file | grep author]} err]} {
            continue
        }
        # Determine last person to commit
        if {[regexp -- {date: ([0-9\/]+)[^\n]+ author: ([a-z]+);} \
                $author_list - commit_date author]} {
            #Format date to yyyymmdd
            regsub -all -- "/" $commit_date "" commit_date
            #Check if author is still a valid member of IOS crypto devtest group
            if { [lsearch $active_owners $author] != -1 } {
                # Run codecheck on file, use full path so it appears in output
                set res [exec /users/sqa/bin/codecheck $area/$file]
                if {[regexp {Code check FAILURES} $res] ||\
                        [regexp {Code check WARNINGS} $res]} {
                    puts "Codecheck errors found in: $file"
                    puts "Errors: $res"
                    # Check if commit is recent enough to trigger notification
                    if {$commit_date < $ref_date} {
                        puts "Not sending notification to $author\n \
                            $area/$file was commited before to $ref_date."
                        append old_commits_list "$area/$file\n \
                            Commited before $ref_date. \
                            No notification sent to $author... \n\n"
                    } else {
                        # Add user to email list
                        append owner_list($author) "$res\n"
                        append admin_list "$author $area/$file\n\n"
                        puts "Author is: $author"
                    }
                } else {
                    puts "No errors found in: $file"
                }
            } else {
                puts "Owner $author for $area/$file is not not an active \
                      member of IOS crypto devtest group"
                append orphan_file_list "$area/$file\n $author is not an \
                            active member of IOS crypto devtest group...\n\n"
            }
        } else {
            puts "Couldn't find owner/commit_date of $area/$file from cvs log"
            append orphan_file_list "$area/$file\n \
                            Author or commit date not found from cvs log...\n\n"
        }
    }
}

# Send email
set owners [array names owner_list]
foreach owner $owners {
    set owner_fid [open $owner_file w+]
    puts $owner_fid "
     A file you recently commited has \"codecheck\" violations.
     You have been identified as the last person to commit changes
     to this file, so you are asked to please correct these
     codecheck errors and re-commit.

     This is an auto-generated message, so do not respond to this email.
     Please contact one of the administrators ($admins) if you have any
     issues with this.

     Listed below are the files that need correcting, along with
     the codecheck errors.  After fixing the errors, please run the
     codecheck tool (also called gatekeeper) to verify all errors have
     been corrected before committing the file.
     Codecheck (also called gatekeeper) can be run as:
       /users/sqa/bin/codecheck <file>
     \n\n"

    puts $owner_fid "$owner_list($owner)\n"
    close $owner_fid

    # Mail out message to owners
    puts "Send mail to $owner"
    exec /usr/bin/mailx -r stg_ipsec_notification@cisco.com -s \"$owner_subject\" $owner < $owner_file
}

# Mail out the admin notification
append admin_list $old_commits_list $orphan_file_list
puts $admin_fid "$admin_list\n"
close $admin_fid
exec /usr/bin/mailx -s \"$admin_subject\" $admins < $admin_file

# -----------------------------------------------------------------------------
#                            CVS MAINTENANCE LOGS
#                            ~~~~~~~~~~~~~~~~~~~~
# $Log: check_libs,v $
# Revision 1.4  2006/10/11 09:55:24  gicarval
#    Added active_owners list to limit the email notification to active members of IOS crypto devtest
#    Added date reference to limit the email notification only for commits after 2006/01/01
#    Added ipsec script files to the list of files checked by the script
#    Changed email reply address to stg_ipsec_notification
#    Changed order by which files are verified against codecheck so that we don't waste time checking for errors in files that IOS crypto devtest doesn't own
#
# Revision 1.3  2006/09/30 02:03:53  gicarval
#    Changed group of admins
#
# Revision 1.2  2006/09/21 18:51:19  tennis
#
# Various updates to some minor support utilities.
#
# Revision 1.1  2006/02/24 12:00:06  tennis
# Initial commit
#
#
# -----------------------------------------------------------------------------
# Local Variables:
# mode: tcl
# End:
