#!/bin/sh
if test -z "$1"
then
echo "\nMissing name!\nUsage: unlock <tedtbed_name|pc_name>\n"
exit
fi

if test -r /auto/vwsqij/sisu-reg/locks/$1.lock
then
echo "\nYou cannot lock \"$1\" because it is in use by: `ls -l /auto/vwsqij/sisu-reg/locks/$1.lock | grep $1 | cut -c16-23`\n"
exit
else
touch /auto/vwsqij/sisu-reg/locks/$1.lock
echo "\n\"$1\" is now locked!\n"
exit
fi
