#!/bin/sh
#\
exec $AUTOTEST/bin/expect "$0" "$@" #
set env(EARMS_SOURCING_CONFIG) 1
package require AtsAuto
package require mysqltcl
global test_name test_priority test_file test_date test_tree test_project test_server CFLOW_DIRECTORY CFLOW_DEBUGS SSH_PWD tims_export tims_variables
global testing baseline solid post start routertype router_image source_directories destination_directories env ROUTERS OPTIONS

puts { Sample: Mandatory autotie  -testbed [testbed] -project [project] -SSH_PWD [ssh_pwd] }
puts { options: -tree [testing baseline solid custom auto] default auto}
puts { options: -CFLOW 		[TRUE FALSE] 		default FALSE }
puts { options: -TIMS  		[TRUE FALSE] 		default FALSE }
puts { options: -EMAIL_WARN  	[any]  			default "none"}
puts { options: -DEBUG  	[ON OFF]    		default OFF   }
puts { options: -MODE   	[NORMAL VERTICAL]    	default NORMAL}


    set man_args {
	-testbed	       ANY
	-project               ANY
	-SSH_PWD	       ANY
    } ; # end mandatory args

    set opt_args {
	-tree		      CHOICES baseline testing solid auto custom
	DEFAULT		      testing
	-CFLOW                CHOICES TRUE FALSE
	DEFAULT 	      FALSE
	-TIMS		      CHOICES TRUE FALSE
	DEFAULT		      FALSE
	-EMAIL_WARN           ANY
	DEFAULT 	      "none"
	-DEBUG		      CHOICES ON OFF
	DEFAULT		      OFF
	-MODE		      CHOICES NORMAL VERTICAL NORMAL_NOSOLID
	DEFAULT		      NORMAL
	-test_clean	      CHOICES baseline testing solid auto custom no
	DEFAULT		      no
	-router_clean         ANY
	DEFAULT		      no
    } ; # end optional args

    set args [lrange $argv 1 $argc]

    parse_dashed_args                     \
        -args $args                       \
        -mandatory_args $man_args         \
        -optional_args $opt_args

# set line [exec ps -ef | grep expect | grep autotie]
# if {[string match -nocase "*$testbed*" $line] && ![string match -nocase "*defunct*" $line]} {
# 	puts " Hey I seem to already be running there in this testbed make ps -ef, are you sure you want to continue, press enter?"
# 	set line [gets stdin]
# }
if { $DEBUG == "OFF" } { 
	#log_user 0
}


set env(_ATS_TESTBED) $testbed
set env(EARMS_SOURCING_CONFIG) 1
source $env(AUTOTEST)/etc/CONFIG.$testbed
aetest::_testbed $env(_ATS_TESTBED)
set testbeds $env(_ATS_TESTBED)
set run_globals(testbed) $testbed



source $env(AUTOTEST)/stg_reg/utils/tie/config/$project.tie
source $env(AUTOTEST)/stg_reg/utils/tie/config/$testbed.clean
source $env(AUTOTEST)/stg_reg/utils/tie/exp/autotie.exp

# check if main 


# CREATE CONFIG FILE TO BE USED FOR THIS TEST
system "cp $env(AUTOTEST)/etc/$testbed.config $env(AUTOTEST)/stg_reg/utils/tie/config/CONFIG.$testbed"
system "cat $env(AUTOTEST)/stg_reg/utils/tie/exp/$project.exp >> $env(AUTOTEST)/stg_reg/utils/tie/config/CONFIG.$testbed"

#Variables for CFLOW, will need to improve this
set FIRST_TIME TRUE
if {$tree == "auto" && $CFLOW == "FALSE"} {
	set enable_tree_selection TRUE
} else {
	set enable_tree_selection FALSE
}

if { $CFLOW =="TRUE" } {
	set tree "custom"
}


set tree_come_back $tree

autotie_running_clean -project $project -testbed $testbed

#autotie_release_lines

#### UPDATE TO LATEST IMAGE ALL BRANCHES
update_images -tree testing
update_images -tree baseline
update_images -tree solid

#### Update links to latest
update_to_latest_img -tree testing
update_to_latest_img -tree baseline
update_to_latest_img -tree solid

if { $test_clean != "no" } {	
	autotie_clean -testbed $testbed -mode slow -tree $test_clean 
	exit
}

if { $router_clean != "no" } {	
	if { $routertype($router_clean)  == "NORMAL_TFTP" || $routertype($router_clean)  == "PAGENT_TFTP" } {
		reload_with_tftpdnld -testbed $testbed -router $router_clean -image $testing($router_clean) -post_config $post($router_clean) -mode slow -start_config $start($router_clean)
	}
	if { $routertype($router_clean)  == "NORMAL_NOTFTP" || $routertype($router_clean)  == "PAGENT_NOTFTP" } {
		 reload_no_tftpdnld -testbed $testbed -router $router_clean -image $testing($router_clean) -post_config $post($router_clean) -mode slow -start_config $start($router_clean) 
	}
	exit
}

#### Clean testbed with testing
#autotie_clean -testbed $testbed -mode slow -tree testing

while { 1 } {
	set time_started [clock seconds]
	# LOAD CONFIG INFORMATION FROM PHP and Running tests
	puts "autotie:Load configuration from PHP \n"
	autotie_load_tests -project $project
	puts "autotie:Load configuration from PHP:done \n"
	
	
	if { $FIRST_TIME == "TRUE" } { update_router_info -project $project }

	puts "autotie:Evaluating if there jobs in queue that we can process \n"
	set tests_in_queue [autotie_test_in_queue -project $project -testbed $testbed]
	if { $tests_in_queue == "False" } {
		sleep 1200
		set tests_in_queue [autotie_test_in_queue -project $project -testbed $testbed]
	}

	if { $tests_in_queue == "False" } {

		puts "autotie: no tests in queue"
		set test_to_run [autotie_select_next_test -mode $MODE -testbed $testbed -tree_selection $enable_tree_selection -project $project]
		set test_id [lindex $test_to_run 0]
		set tree_selected [lindex $test_to_run 1]
		if { $tree_selected != "same" } { set tree $tree_selected } 
		if { $test_id != "same" } { set test_selected $test_id } 
	
		#Inform database that test was selected
		autotie_running_info -ID $test_selected -project $project -testbed $testbed -test $test_name($test_selected) -tree $tree -Date $time_started

		# SEE IF THERE ARE NEW IMAGES
		if { $tree != "custom" } {
			update_images -tree $tree
			update_to_latest_img -tree $tree		
			puts "tie-Finish doing image update"
		} 
		
		#SYNC VARIABLES TO IMAGES
		if { $FIRST_TIME == "TRUE" } { 
			autotie_clean -testbed $testbed -mode slow -tree $tree 
		} else { 
			autotie_clean -testbed $testbed -mode normal -tree $tree -ID $test_selected 
			autotie_clean -testbed $testbed -mode quick -tree $tree
		}
	} elseif { $tests_in_queue == "True" } {
		puts "tests in queue, select test to run"
		set test_to_run [tie_queue_test_to_run -testbed $testbed -project $project]
		set test_id [lindex $test_to_run 0]
		set tree_selected [lindex $test_to_run 1]
		if { $tree_selected != "same" } { set tree $tree_selected } 
		if { $test_id != "same" } { set test_selected $test_id } 

		if { $tree != "custom" } {
			update_to_latest_img -tree $tree		
			puts "tie-Finish doing image update"
		} 

		puts "##### Inform database that test started #######"	
		autotie_running_info -ID $test_selected -project $project -testbed $testbed -test $test_name($test_selected) -tree $tree -Date $time_started
		puts "##### STARTING CLEAN                    #######"
		autotie_clean -testbed $testbed -mode normal -tree $tree -ID $test_selected 
		puts "##### Overright all router in testbed with a clean config"
		autotie_clean -testbed $testbed -mode quick -tree $tree

		autotie_load_debug_commands -ID $test_selected


	}

	#IF CLOW MODE RUN EXTRACT DATA FROM ROUTERS 97
	if { $CFLOW == "TRUE" } { tie_cflow_clean -testID $test_selected -testbed $testbed -project $project }
	

	tie_run_before_test -tree $tree -project $project -testid $test_selected
	#SUBMIT TEST

	#LOAD TEST SETTING COPY FILES, ENVIROMENT AND CHANGES BASED ON CLASS
	tie_load_test_settings -ID $test_selected -tree $tree

	puts "SUBMIT TEST -testID $test_selected -testbed $testbed -tree $tree server $test_server($test_selected)"
	
      
	
	#IMPROVE THIS PART IS UGLY
	if { $test_server($test_selected) == "" } {
		autotie_submit_test -testID $test_selected -testbed $testbed -tree $tree -project $project -TIMS $TIMS 
	} else {
		autotie_submit_test_server -testID $test_selected -testbed $testbed -tree $tree -project $project -TIMS $TIMS -server $test_server($test_selected)
	}
	#CFLOW RUN EXTRACT DATA FROM ROUTERS
	if { $CFLOW == "TRUE" } {
		tie_cflow_extract -testID $test_selected -testbed $testbed -project $project
	}
	#####
	tie_run_after_test -tree $tree -project $project -testid $test_selected

	#detect user exit
	autotie_detect_stop -project $project -testbed $testbed
	#Inform database that test was finished exit program if exit detected
	autotie_running_delete -ID $test_selected -project $project -testbed $testbed -test $test_name($test_selected) -tree $tree -Date $time_started


	#START ALL OVER AGAIN
	set FIRST_TIME "FALSE"
	#Tree come back (just in case something strange happen)
	set tree $tree_come_back
	#exit lets try it for real
}



### IMPORTANT THINGS TO DO
# REMOVE THE COPY OF THE TEST ALL OVER
# REMOVE THE CHECKS OF IF's IN THE MAIN SCRIPT
# FIX autoeasy
# FIX GLOBAL ENVIROMENTS 
# FIX SAME VARIABLE FOR SAME THING 
